[package]
name = "state_machines"
version = "0.1.0"
authors = ["Roni Peled <roni@mediajel.com>"]

[dependencies]
drivers = { path = "../drivers" }
rppal = "0.8.1"

[lib]
name = "state_machines"
path = "src/lib.rs"