[package]
name = "simulation"
version = "0.1.0"
authors = ["Roni Peled <roni.peled1994@gmail.com>"]

[dependencies]
three = "0.3.1"
mint = "0.5.0"
rppal = { path = "../rppal_stubs" }

[lib]
name = "youpassbutter"
path = "src/lib.rs"

[[bin]]
name = "youpassbutter_runner"
path = "src/main.rs"