[package]
name = "simulation"
version = "0.1.0"
authors = ["Roni Peled <roni.peled1994@gmail.com>"]

[dependencies]
ws = "0.7.9"
mint = "0.5.0"
rppal = "0.8.1"

[lib]
name = "youpassbutter"
path = "src/lib.rs"

[[bin]]
name = "youpassbutter_runner"
path = "src/main.rs"