#ifndef PINOUT_DEFINITIONS_H
#define PINOUT_DEFINITIONS_H

#include <semaphore.h>

#define OUTPUT_E_LEFT 26
#define OUTPUT_IN_1_LEFT 19
#define OUTPUT_IN_2_LEFT 13
#define OUTPUT_E_RIGHT 22
#define OUTPUT_IN_3_RIGHT 6
#define OUTPUT_IN_4_RIGHT 5

#define MICRO_SEC_IN_SEC 1000000

#define MPU6050_ADDRESS 0x68

#endif // PINOUT_DEFINITIONS_H