[package]
name = "simulation"
version = "0.1.0"
authors = ["Roni Peled <roni.peled1994@gmail.com>"]

[dependencies]
three = "0.3.1"
mint = "0.5.0"
state_machines = { path = "../state_machines" }

[lib]
name = "simulation"
path = "src/lib.rs"

[[bin]]
name = "simulation_runner"
path = "src/main.rs"