[package]
name = "drivers"
version = "0.1.0"
authors = ["Roni Peled <roni.peled1994@gmail.com>"]

[target.x86_64-apple-darwin.dependencies]
rppal = { path = "../rppal_stubs" }

[lib]
name = "drivers"
path = "src/lib.rs"